USE [master]
GO

/****** Object:  Database [HiTechDB]    Script Date: 2019-08-03 9:11:00 PM ******/
CREATE DATABASE [HiTechDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HiTechDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\HiTechDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HiTechDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\HiTechDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [HiTechDB] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HiTechDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HiTechDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HiTechDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HiTechDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HiTechDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HiTechDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [HiTechDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HiTechDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HiTechDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HiTechDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HiTechDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HiTechDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HiTechDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HiTechDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HiTechDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HiTechDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HiTechDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HiTechDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HiTechDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HiTechDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HiTechDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HiTechDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HiTechDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HiTechDB] SET RECOVERY FULL 
GO

ALTER DATABASE [HiTechDB] SET  MULTI_USER 
GO

ALTER DATABASE [HiTechDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HiTechDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HiTechDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HiTechDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [HiTechDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HiTechDB] SET QUERY_STORE = OFF
GO

USE [HiTechDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [HiTechDB] SET  READ_WRITE 
GO

